.gobuildenv: &gobuildenv
  image: golang:1.10-stretch
  before_script:
    - BUILD_DIR=$GOPATH/src/$CI_PROJECT_PATH
    - mkdir -p $BUILD_DIR && rmdir $BUILD_DIR
    - ln -s `pwd` $BUILD_DIR
    - cd $BUILD_DIR

build:
  stage: build
  <<: *gobuildenv
  script:
    # check everything builds well
    - go build ./...
    # unit tests
    # - ./code-coverage.sh
    # create package
    - go build -o ./dist/cxdig .
    - go build -o ./dist/dumbtool ./test_suite/dumbtool
  artifacts:
    expire_in: 1 week
    paths:
      - dist/

test_cmake:
  stage: test
  image: buildpack-deps:xenial-scm
  before_script:
    - git clone https://github.com/Kitware/CMake --depth 120
  script:
    - ./dist/cxdig scan -q CMake
    - if [ ! -f "CMake.cxray/commits.json" ]; then echo "commits JSON file is missing" && exit 1; fi
    - if [ ! -f "CMake.cxray/referential.json" ]; then echo "referential JSON file is missing" && exit 1; fi
    - ./dist/cxdig sample -q --cmd "./dist/dumbtool --id {commit.id} --name {name} {path}" CMake --limit 100 | tee test-output.log
    #- NBRETURN=$(cat test-output.log | wc -l)
    #- if [ "$NBRETURN" != "100" ]; then echo "Found $NBRETURN lines, expected 100" && exit 1; fi

release:
  stage: deploy
  <<: *gobuildenv
  dependencies: []
  script:
    # set version value
    - VERSION="$CI_COMMIT_REF_NAME"
    - DATE="`date +%Y.%m.%d`"
    # build without debugging symbols
    - LDFLAGS="-s"
    # inject version info
    - LDFLAGS="$LDFLAGS -X $CI_PROJECT_PATH/cmd.softwareVersion=$VERSION"
    # multiple builds
    - go get github.com/mitchellh/gox
    - gox -arch "amd64 arm" -os="!netbsd" -ldflags "$LDFLAGS" -output "dist/${CI_PROJECT_NAME}_{{.OS}}_{{.Arch}}"
    # check version is OK
    - PRINTED_VERSION=$(./dist/cxdig_linux_amd64 version -q)
    - '[[ "$PRINTED_VERSION" == v* ]] || (echo "Skipping invalid version: $PRINTED_VERSION")'
  only:
    - master
  artifacts:
    expire_in: 1 week
    paths:
      - dist/
